load("@rules_python//python:py_library.bzl", "py_library")

package(
    default_visibility=["//visibility:public"],
)

py_library(
    name = "talk_node",
    srcs = ["talk_node.py"],
    deps = [
    ]
)
