# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatureTemplate',
            fields=[
                ('creature_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('regen_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('is_pet_stat', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemTemplate',
            fields=[
                ('item_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ability', models.IntegerField()),
                ('level', models.IntegerField()),
                ('value', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('charges', models.IntegerField()),
                ('protection', models.IntegerField()),
                ('can_augment', models.BooleanField(default=False)),
                ('extra_description', models.IntegerField()),
                ('graphic_sheet', models.IntegerField()),
                ('graphic_template', models.IntegerField()),
                ('which_icon_ground', models.IntegerField()),
                ('which_icon_inven', models.IntegerField()),
                ('graphic_color_adj', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemVariety',
            fields=[
                ('variety_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('stat_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='itemtemplate',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geneforge5.ItemVariety'),
        ),
        migrations.AddField(
            model_name='itemstat',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geneforge5.ItemTemplate'),
        ),
        migrations.AddField(
            model_name='itemstat',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geneforge5.Stat'),
        ),
    ]
