# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('geneforge5', '0001_initial'), ('geneforge5', '0002_auto_20171021_1941'), ('geneforge5', '0003_auto_20171022_2154'), ('geneforge5', '0004_zoneitem'), ('geneforge5', '0005_zone'), ('geneforge5', '0006_auto_20171102_0442'), ('geneforge5', '0007_objecttemplate'), ('geneforge5', '0008_objecttemplate_name'), ('geneforge5', '0009_zoneobject'), ('geneforge5', '0010_auto_20171104_2049')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatureTemplate',
            fields=[
                ('creature_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('cr_name', models.CharField(max_length=200)),
                ('cr_base_level', models.IntegerField(default=0)),
                ('cr_bonus_aps', models.IntegerField(null=True)),
                ('cr_default_aggression', models.IntegerField(default=0)),
                ('cr_default_courage', models.IntegerField(null=True)),
                ('cr_default_script', models.CharField(default=0, max_length=200)),
                ('cr_default_strategy', models.IntegerField(null=True)),
                ('cr_effect_when_slain', models.IntegerField(null=True)),
                ('cr_energy_regen_rate', models.IntegerField(null=True)),
                ('cr_graphic_appearadj', models.IntegerField(null=True)),
                ('cr_graphic_coloradj', models.IntegerField(null=True)),
                ('cr_graphic_template', models.IntegerField(default=0)),
                ('cr_max_energy', models.IntegerField(null=True)),
                ('cr_max_essence', models.IntegerField(null=True)),
                ('cr_max_health', models.IntegerField(null=True)),
                ('cr_missile_firing_height', models.IntegerField(null=True)),
                ('cr_multiple_facings', models.IntegerField(null=True)),
                ('cr_nimbleness', models.IntegerField(null=True)),
                ('cr_regen_rate', models.IntegerField(null=True)),
                ('cr_size', models.IntegerField(default=0)),
                ('cr_sound_when_slain', models.IntegerField(null=True)),
                ('cr_stain_when_slain', models.IntegerField(null=True)),
                ('cr_vert_adjust', models.IntegerField(null=True)),
                ('cr_walk_speed', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('is_pet_stat', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemTemplate',
            fields=[
                ('item_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ability', models.IntegerField()),
                ('level', models.IntegerField()),
                ('value', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('charges', models.IntegerField()),
                ('protection', models.IntegerField()),
                ('can_augment', models.BooleanField(default=False)),
                ('extra_description', models.IntegerField()),
                ('graphic_sheet', models.IntegerField()),
                ('graphic_template', models.IntegerField()),
                ('which_icon_ground', models.IntegerField()),
                ('which_icon_inven', models.IntegerField()),
                ('graphic_color_adj', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemVariety',
            fields=[
                ('variety_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('stat_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='itemtemplate',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geneforge5.ItemVariety'),
        ),
        migrations.AddField(
            model_name='itemstat',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geneforge5.ItemTemplate'),
        ),
        migrations.AddField(
            model_name='itemstat',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geneforge5.Stat'),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='ability',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='charges',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='extra_description',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='graphic_color_adj',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='graphic_sheet',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='graphic_template',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='protection',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='which_icon_ground',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='which_icon_inven',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='ZoneItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_pos', models.IntegerField()),
                ('y_pos', models.IntegerField()),
                ('charges', models.IntegerField(null=True)),
                ('properties', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geneforge5.ItemTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('town_script', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='zoneitem',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geneforge5.Zone'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ObjectTemplate',
            fields=[
                ('object_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('graphic_template', models.IntegerField(null=True)),
                ('graphic_sheet', models.IntegerField(null=True)),
                ('base_icon_num', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('blockage_type', models.IntegerField(null=True)),
                ('can_target', models.IntegerField(null=True)),
                ('start_health', models.IntegerField(null=True)),
                ('default_script', models.CharField(max_length=200)),
                ('number_anim_steps_destroyed', models.IntegerField(null=True)),
                ('which_icon_destroyed', models.IntegerField(null=True)),
                ('block_move_when_destroyed', models.IntegerField(null=True)),
                ('object_type', models.IntegerField(null=True)),
                ('effect_when_slain', models.IntegerField(null=True)),
                ('glow_type', models.IntegerField(null=True)),
                ('anim_in_reverse', models.IntegerField(null=True)),
                ('glow_trans', models.IntegerField(null=True)),
                ('num_anim_steps', models.IntegerField(null=True)),
                ('object_trait', models.IntegerField(null=True)),
                ('in_space_offset_y', models.IntegerField(null=True)),
                ('in_space_offset_x', models.IntegerField(null=True)),
                ('graphic_coloradj', models.IntegerField(null=True)),
                ('part_of_terrain', models.IntegerField(null=True)),
                ('graphic_appearadj', models.IntegerField(null=True)),
                ('light_level', models.IntegerField(null=True)),
                ('glow_offset', models.IntegerField(null=True)),
                ('name', models.CharField(default='hi', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_pos', models.IntegerField()),
                ('y_pos', models.IntegerField()),
                ('x_offset', models.IntegerField()),
                ('y_offset', models.IntegerField()),
                ('override_script', models.CharField(max_length=200)),
                ('flags', models.CharField(max_length=200)),
                ('object_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geneforge5.ObjectTemplate')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geneforge5.Zone')),
            ],
        ),
        migrations.AddField(
            model_name='zoneitem',
            name='x_offset',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zoneitem',
            name='y_offset',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
