# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneforge5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtemplate',
            name='ability',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='charges',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='extra_description',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='graphic_color_adj',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='graphic_sheet',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='graphic_template',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='protection',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='which_icon_ground',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='which_icon_inven',
            field=models.IntegerField(null=True),
        ),
    ]
