# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneforge5', '0001_squashed_0010_auto_20171104_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creaturetemplate',
            name='cr_base_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='creaturetemplate',
            name='cr_default_aggression',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='creaturetemplate',
            name='cr_default_script',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='creaturetemplate',
            name='cr_graphic_template',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='creaturetemplate',
            name='cr_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='objecttemplate',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
