# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-03 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geneforge5', '0002_auto_20180123_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneCreature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_script', models.CharField(max_length=200)),
                ('x_pos', models.IntegerField()),
                ('y_pos', models.IntegerField()),
                ('x_offset', models.IntegerField()),
                ('y_offset', models.IntegerField()),
                ('flags', models.CharField(max_length=200)),
                ('extra_items', models.CharField(max_length=200)),
                ('attitude', models.IntegerField(null=True)),
                ('personality', models.IntegerField(null=True)),
                ('creature_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geneforge5.CreatureTemplate')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geneforge5.Zone')),
            ],
        ),
    ]
