# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneforge5', '0002_auto_20171021_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creaturetemplate',
            old_name='name',
            new_name='cr_name',
        ),
        migrations.RemoveField(
            model_name='creaturetemplate',
            name='regen_rate',
        ),
        migrations.AddField(
            model_name='creaturetemplate',
            name='cr_base_level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creaturetemplate',
            name='cr_bonus_aps',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='creaturetemplate',
            name='cr_default_aggression',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creaturetemplate',
            name='cr_default_courage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='creaturetemplate',
            name='cr_default_script',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creaturetemplate',
            name='cr_default_strategy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='creaturetemplate',
            name='cr_effect_when_slain',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='creaturetemplate',
            name='cr_energy_regen_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='creaturetemplate',
            name='cr_graphic_appearadj',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='creaturetemplate',
            name='cr_graphic_coloradj',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='creaturetemplate',
            name='cr_graphic_template',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creaturetemplate',
            name='cr_max_energy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='creaturetemplate',
            name='cr_max_essence',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='creaturetemplate',
            name='cr_max_health',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='creaturetemplate',
            name='cr_missile_firing_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='creaturetemplate',
            name='cr_multiple_facings',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='creaturetemplate',
            name='cr_nimbleness',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='creaturetemplate',
            name='cr_regen_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='creaturetemplate',
            name='cr_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creaturetemplate',
            name='cr_sound_when_slain',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='creaturetemplate',
            name='cr_stain_when_slain',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='creaturetemplate',
            name='cr_vert_adjust',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='creaturetemplate',
            name='cr_walk_speed',
            field=models.IntegerField(null=True),
        ),
    ]
