# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geneforge5', '0003_auto_20171022_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField(default=0)),
                ('x_pos', models.IntegerField()),
                ('y_pos', models.IntegerField()),
                ('charges', models.IntegerField(null=True)),
                ('properties', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geneforge5.ItemTemplate')),
            ],
        ),
    ]
