# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-03 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneforge5', '0003_zonecreature'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonecreature',
            name='zone_creature_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
