# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-03 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneforge5', '0004_zonecreature_zone_creature_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstat',
            name='is_pet_stat',
            field=models.IntegerField(),
        ),
    ]
