# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneforge5', '0004_zoneitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('town_script', models.CharField(max_length=200)),
            ],
        ),
    ]
