# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geneforge5', '0005_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoneitem',
            name='zone_id',
        ),
        migrations.AddField(
            model_name='zoneitem',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geneforge5.Zone'),
            preserve_default=False,
        ),
    ]
