# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneforge5', '0006_auto_20171102_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectTemplate',
            fields=[
                ('object_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('graphic_template', models.IntegerField(null=True)),
                ('graphic_sheet', models.IntegerField(null=True)),
                ('base_icon_num', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('blockage_type', models.IntegerField(null=True)),
                ('can_target', models.IntegerField(null=True)),
                ('start_health', models.IntegerField(null=True)),
                ('default_script', models.CharField(max_length=200)),
                ('number_anim_steps_destroyed', models.IntegerField(null=True)),
                ('which_icon_destroyed', models.IntegerField(null=True)),
                ('block_move_when_destroyed', models.IntegerField(null=True)),
                ('object_type', models.IntegerField(null=True)),
                ('effect_when_slain', models.IntegerField(null=True)),
                ('glow_type', models.IntegerField(null=True)),
                ('anim_in_reverse', models.IntegerField(null=True)),
                ('glow_trans', models.IntegerField(null=True)),
                ('num_anim_steps', models.IntegerField(null=True)),
                ('object_trait', models.IntegerField(null=True)),
                ('in_space_offset_y', models.IntegerField(null=True)),
                ('in_space_offset_x', models.IntegerField(null=True)),
                ('graphic_coloradj', models.IntegerField(null=True)),
                ('part_of_terrain', models.IntegerField(null=True)),
                ('graphic_appearadj', models.IntegerField(null=True)),
                ('light_level', models.IntegerField(null=True)),
                ('glow_offset', models.IntegerField(null=True)),
            ],
        ),
    ]
