# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneforge5', '0007_objecttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecttemplate',
            name='name',
            field=models.CharField(default='hi', max_length=200),
            preserve_default=False,
        ),
    ]
