# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-03 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geneforge5', '0007_auto_20180203_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.IntegerField()),
                ('state', models.IntegerField(default=-1)),
                ('next_state', models.IntegerField(default=-1)),
                ('condition', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=2000)),
                ('code', models.CharField(max_length=2000)),
                ('action', models.CharField(max_length=200)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geneforge5.Zone')),
            ],
        ),
        migrations.CreateModel(
            name='CreatureTemplateItemDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.IntegerField()),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geneforge5.CreatureTemplate')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geneforge5.ItemTemplate')),
            ],
        ),
    ]
