# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneforge5', '0008_conversationnode_creaturetemplateitemdrop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonecreature',
            name='extra_items',
        ),
        migrations.AddField(
            model_name='zonecreature',
            name='extraItem1_chance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='zonecreature',
            name='extraItem1_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='zonecreature',
            name='extraItem2_chance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='zonecreature',
            name='extraItem2_id',
            field=models.IntegerField(null=True),
        ),
    ]
