# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geneforge5', '0008_objecttemplate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_pos', models.IntegerField()),
                ('y_pos', models.IntegerField()),
                ('x_offset', models.IntegerField()),
                ('y_offset', models.IntegerField()),
                ('override_script', models.CharField(max_length=200)),
                ('flags', models.CharField(max_length=200)),
                ('object_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geneforge5.ObjectTemplate')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geneforge5.Zone')),
            ],
        ),
    ]
