# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneforge5', '0009_zoneobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoneitem',
            name='x_offset',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zoneitem',
            name='y_offset',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
