# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneforge5', '0009_auto_20180205_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonecreature',
            name='extraItem1_chance',
        ),
        migrations.RemoveField(
            model_name='zonecreature',
            name='extraItem1_id',
        ),
        migrations.RemoveField(
            model_name='zonecreature',
            name='extraItem2_chance',
        ),
        migrations.RemoveField(
            model_name='zonecreature',
            name='extraItem2_id',
        ),
        migrations.AddField(
            model_name='zonecreature',
            name='extra_items',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
